version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mail
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: npm run start